// default package
// Generated Dec 1, 2017 6:06:17 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "ignitiv")
public class Brand implements java.io.Serializable {

	private Integer id;
	private String brandCode;
	private Integer imageId;
	private String brandDesc;
	private String homeExclusiveInd;
	private String language;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String batchId;
	private String item;

	public Brand() {
	}

	public Brand(String brandCode, Integer imageId, String brandDesc, String homeExclusiveInd, String language,
			String isProcessSuccess, Integer errorCode, String errorDesc, String batchId, String item) {
		this.brandCode = brandCode;
		this.imageId = imageId;
		this.brandDesc = brandDesc;
		this.homeExclusiveInd = homeExclusiveInd;
		this.language = language;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.batchId = batchId;
		this.item = item;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BRAND_CODE", length = 64)
	public String getBrandCode() {
		return this.brandCode;
	}

	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	@Column(name = "IMAGE_ID")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Column(name = "BRAND_DESC", length = 65535)
	public String getBrandDesc() {
		return this.brandDesc;
	}

	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc;
	}

	@Column(name = "HOME_EXCLUSIVE_IND", length = 1)
	public String getHomeExclusiveInd() {
		return this.homeExclusiveInd;
	}

	public void setHomeExclusiveInd(String homeExclusiveInd) {
		this.homeExclusiveInd = homeExclusiveInd;
	}

	@Column(name = "Language", length = 11)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "BATCH_ID", length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	@Column(name = "ITEM", length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String toString(){
		return "brandCode  "+brandCode+" \n ";
	}
}
