package com.homehardware.model;
// Generated Nov 20, 2017 5:59:27 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChangedImages generated by hbm2java.
 */
@Entity
@Table(name = "changed_images", catalog = "ignitiv")
public class ChangedImages implements java.io.Serializable {
  
  /**
   * .
   */
  private static final long serialVersionUID = 8302900834228255750L;
  private Integer id;
  private String item;
  private Integer imageId;
  private String imageType;
  private Integer imageSeqNbr;
  private String furnitureInd;
  private String isProcessSuccess;
  private Integer errorCode;
  private String errorDesc;
  
  public ChangedImages() {
  }
  
  /**
   * .
   */
  public ChangedImages(String item, Integer imageId,
      String imageType, Integer imageSeqNbr, String furnitureInd,
      String isProcessSuccess, Integer errorCode, String errorDesc) {
    this.item = item;
    this.imageId = imageId;
    this.imageType = imageType;
    this.imageSeqNbr = imageSeqNbr;
    this.furnitureInd = furnitureInd;
    this.isProcessSuccess = isProcessSuccess;
    this.errorCode = errorCode;
    this.errorDesc = errorDesc;
  }
  
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }
  
  public void setId(Integer id) {
    this.id = id;
  }
  
  @Column(name = "ITEM", length = 64)
  public String getItem() {
    return this.item;
  }
  
  public void setItem(String item) {
    this.item = item;
  }
  
  @Column(name = "IMAGE_ID")
  public Integer getImageId() {
    return this.imageId;
  }
  
  public void setImageId(Integer imageId) {
    this.imageId = imageId;
  }
  
  @Column(name = "IMAGE_TYPE", length = 64)
  public String getImageType() {
    return this.imageType;
  }
  
  public void setImageType(String imageType) {
    this.imageType = imageType;
  }
  
  @Column(name = "IMAGE_SEQ_NBR")
  public Integer getImageSeqNbr() {
    return this.imageSeqNbr;
  }
  
  public void setImageSeqNbr(Integer imageSeqNbr) {
    this.imageSeqNbr = imageSeqNbr;
  }
  
  @Column(name = "FURNITURE_IND", length = 1)
  public String getFurnitureInd() {
    return this.furnitureInd;
  }
  
  public void setFurnitureInd(String furnitureInd) {
    this.furnitureInd = furnitureInd;
  }
  
  @Column(name = "IS_PROCESS_SUCCESS", length = 1)
  public String getIsProcessSuccess() {
    return this.isProcessSuccess;
  }
  
  public void setIsProcessSuccess(String isProcessSuccess) {
    this.isProcessSuccess = isProcessSuccess;
  }
  
  @Column(name = "ERROR_CODE")
  public Integer getErrorCode() {
    return this.errorCode;
  }
  
  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }
  
  @Column(name = "ERROR_DESC", length = 65535)
  public String getErrorDesc() {
    return this.errorDesc;
  }
  
  public void setErrorDesc(String errorDesc) {
    this.errorDesc = errorDesc;
  }
  
}
