package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ecofees generated by hbm2java
 */
@Entity
@Table(name = "ecofees", catalog = "ignitiv")
public class EcoFees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer item;
	private String prov;
	private Double feeAmt;

	public EcoFees() {
	}

	public EcoFees(Integer item, String prov, Double feeAmt) {
		this.item = item;
		this.prov = prov;
		this.feeAmt = feeAmt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM")
	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer item) {
		this.item = item;
	}

	@Column(name = "PROV", length = 64)
	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	@Column(name = "FEE_AMT", precision = 22, scale = 0)
	public Double getFeeAmt() {
		return this.feeAmt;
	}

	public void setFeeAmt(Double feeAmt) {
		this.feeAmt = feeAmt;
	}

}
