// default package
// Generated Nov 22, 2017 11:27:21 AM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EcoFees generated by hbm2java
 */
@Entity
@Table(name = "eco_fees", catalog = "ignitiv")
public class EcoFees implements java.io.Serializable {

	private Integer id;
	private String item;
	private String prov;
	private double feeAmt;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;

	public EcoFees() {
	}

	public EcoFees(String item, String prov, double feeAmt) {
		this.item = item;
		this.prov = prov;
		this.feeAmt = feeAmt;
	}

	public EcoFees(String item, String prov, double feeAmt, String isProcessSuccess, Integer errorCode,
			String errorDesc) {
		this.item = item;
		this.prov = prov;
		this.feeAmt = feeAmt;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM", nullable = false, length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "PROV", nullable = false, length = 64)
	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	@Column(name = "FEE_AMT", nullable = false, precision = 22, scale = 0)
	public double getFeeAmt() {
		return this.feeAmt;
	}

	public void setFeeAmt(double feeAmt) {
		this.feeAmt = feeAmt;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

}
