// default package
// Generated Dec 26, 2017 7:02:02 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gtin generated by hbm2java
 */
@Entity
@Table(name = "gtin", catalog = "ignitiv")
public class Gtin implements java.io.Serializable {

	private Integer id;
	private String item;
	private String gtin;
	private String batchId;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String status;

	public Gtin() {
	}

	public Gtin(String gtin) {
		this.gtin = gtin;
	}

	public Gtin(String item, String gtin, String batchId, String isProcessSuccess, Integer errorCode, String errorDesc,
			String status) {
		this.item = item;
		this.gtin = gtin;
		this.batchId = batchId;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM", length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "GTIN", nullable = false, length = 64)
	public String getGtin() {
		return this.gtin;
	}

	public void setGtin(String gtin) {
		this.gtin = gtin;
	}

	@Column(name = "BATCH_ID", length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
