package com.homehardware.model;
// Generated Dec 4, 2017 12:36:51 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HhBatchDetails generated by hbm2java
 */
@Entity
@Table(name = "hh_batch_details", catalog = "ignitiv")
public class HhBatchDetails implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Long id;
  private String batchId;
  private String status;
  private Date startdate;
  private Date enddate;
  private Integer filesPerBatch;

  public HhBatchDetails() {
  }

  public HhBatchDetails(String batchId, String status, Date startdate, Date enddate, Integer filesPerBatch) {
    this.batchId = batchId;
    this.status = status;
    this.startdate = startdate;
    this.enddate = enddate;
    this.filesPerBatch = filesPerBatch;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "id", unique = true, nullable = false)
  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @Column(name = "batch_id", length = 75)
  public String getBatchId() {
    return this.batchId;
  }

  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }

  @Column(name = "status", length = 45)
  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "startdate", length = 19)
  public Date getStartdate() {
    return this.startdate;
  }

  public void setStartdate(Date startdate) {
    this.startdate = startdate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "enddate", length = 19)
  public Date getEnddate() {
    return this.enddate;
  }

  public void setEnddate(Date enddate) {
    this.enddate = enddate;
  }

  @Column(name = "files_per_batch")
  public Integer getFilesPerBatch() {
    return this.filesPerBatch;
  }

  public void setFilesPerBatch(Integer filesPerBatch) {
    this.filesPerBatch = filesPerBatch;
  }

}
