package com.homehardware.model;
// Generated Dec 4, 2017 2:17:05 PM by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import com.hh.integration.constants.Constant;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.camel.dataformat.bindy.annotation.CsvRecord;
import org.apache.camel.dataformat.bindy.annotation.DataField;

/**
 * Hierarchy generated by hbm2java.
 */
@Entity
@Table(name = "hierarchy", catalog = "ignitiv")
@CsvRecord(separator = "\\|", skipFirstLine = true)
public class Hierarchy implements java.io.Serializable {

        private static final long serialVersionUID = 1L;
        private Integer id;
        @DataField(pos = Constant.int_1)
        private Integer rmsDivision;
        @DataField(pos = Constant.int_2)
        private String divisionNameEnglish;
        @DataField(pos = Constant.int_3)
        private String divisionNameFrench;
        @DataField(pos = Constant.int_4)
        private Integer rmsDept;
        @DataField(pos = Constant.int_5)
        private String deptNameEnglish;
        @DataField(pos = Constant.int_6)
        private String deptNameFrench;
        @DataField(pos = Constant.int_7)
        private Integer rmsCategory;
        @DataField(pos = Constant.int_8)
        private String catNameEnglish;
        @DataField(pos = Constant.int_9)
        private String catNameFrench;
        @DataField(pos = Constant.int_10)
        private Integer rmsProductClass;
        @DataField(pos = Constant.int_11)
        private String productClassNameEnglish;
        @DataField(pos = Constant.int_12)
        private String productClassNameFrench;
        @DataField(pos = Constant.int_13)
        private Integer rmsFinelineClass;
        @DataField(pos = Constant.int_14)
        private String flcNameEnglish;
        @DataField(pos = Constant.int_15)
        private String flcNameFrench;
        private String isProcessSuccess;
        private Integer errorCode;
        private String errorDesc;
        private String batchId;
        private String status;
        private String createBy;
        private Date createDate;
        private String updateBy;
        private Date updateDate;

        public Hierarchy() {
        }

        public Hierarchy(final Integer rmsDivision, final String divisionNameEnglish,
                        final String divisionNameFrench, final Integer rmsDept,
                        final String deptNameEnglish, final String deptNameFrench,
                        final Integer rmsCategory, final String catNameEnglish,
                        final String catNameFrench, final Integer rmsProductClass,
                        final String productClassNameEnglish, final String productClassNameFrench,
                        final Integer rmsFinelineClass, final String flcNameEnglish,
                        final String flcNameFrench, final String isProcessSuccess,
                        final Integer errorCode, final String errorDesc, final String batchId,
                        final String status, final String createBy, final Date createDate,
                        final String updateBy, final Date updateDate) {
                this.rmsDivision = rmsDivision;
                this.divisionNameEnglish = divisionNameEnglish;
                this.divisionNameFrench = divisionNameFrench;
                this.rmsDept = rmsDept;
                this.deptNameEnglish = deptNameEnglish;
                this.deptNameFrench = deptNameFrench;
                this.rmsCategory = rmsCategory;
                this.catNameEnglish = catNameEnglish;
                this.catNameFrench = catNameFrench;
                this.rmsProductClass = rmsProductClass;
                this.productClassNameEnglish = productClassNameEnglish;
                this.productClassNameFrench = productClassNameFrench;
                this.rmsFinelineClass = rmsFinelineClass;
                this.flcNameEnglish = flcNameEnglish;
                this.flcNameFrench = flcNameFrench;
                this.isProcessSuccess = isProcessSuccess;
                this.errorCode = errorCode;
                this.errorDesc = errorDesc;
                this.batchId = batchId;
                this.status = status;
                this.createBy = createBy;
                this.createDate = createDate;
                this.updateBy = updateBy;
                this.updateDate = updateDate;
        }

        @Id
        @GeneratedValue(strategy = IDENTITY)
        @Column(name = "id", unique = true, nullable = false)
        public final Integer getId() {
                return this.id;
        }

        public final void setId(final Integer id) {
                this.id = id;
        }

        @Column(name = "RMS_DIVISION")
        public final Integer getRmsDivision() {
                return this.rmsDivision;
        }

        public final void setRmsDivision(final Integer rmsDivision) {
                this.rmsDivision = rmsDivision;
        }

        @Column(name = "DIVISION_NAME_ENGLISH", length = Constant.int_45)
        public final String getDivisionNameEnglish() {
                return this.divisionNameEnglish;
        }

        public final void setDivisionNameEnglish(final String divisionNameEnglish) {
                this.divisionNameEnglish = divisionNameEnglish;
        }

        @Column(name = "DIVISION_NAME_FRENCH", length = Constant.int_45)
        public final String getDivisionNameFrench() {
                return this.divisionNameFrench;
        }

        public final void setDivisionNameFrench(final String divisionNameFrench) {
                this.divisionNameFrench = divisionNameFrench;
        }

        @Column(name = "RMS_DEPT")
        public final Integer getRmsDept() {
                return this.rmsDept;
        }

        public final void setRmsDept(final Integer rmsDept) {
                this.rmsDept = rmsDept;
        }

        @Column(name = "DEPT_NAME_ENGLISH", length = Constant.int_45)
        public final String getDeptNameEnglish() {
                return this.deptNameEnglish;
        }

        public final void setDeptNameEnglish(final String deptNameEnglish) {
                this.deptNameEnglish = deptNameEnglish;
        }

        @Column(name = "DEPT_NAME_FRENCH", length = Constant.int_45)
        public final String getDeptNameFrench() {
                return this.deptNameFrench;
        }

        public final void setDeptNameFrench(final String deptNameFrench) {
                this.deptNameFrench = deptNameFrench;
        }

        @Column(name = "RMS_CATEGORY")
        public final Integer getRmsCategory() {
                return this.rmsCategory;
        }

        public final void setRmsCategory(final Integer rmsCategory) {
                this.rmsCategory = rmsCategory;
        }

        @Column(name = "CAT_NAME_ENGLISH", length = Constant.int_45)
        public final String getCatNameEnglish() {
                return this.catNameEnglish;
        }

        public final void setCatNameEnglish(final String catNameEnglish) {
                this.catNameEnglish = catNameEnglish;
        }

        @Column(name = "CAT_NAME_FRENCH", length = Constant.int_45)
        public final String getCatNameFrench() {
                return this.catNameFrench;
        }

        public final void setCatNameFrench(final String catNameFrench) {
                this.catNameFrench = catNameFrench;
        }

        @Column(name = "RMS_PRODUCT_CLASS")
        public final Integer getRmsProductClass() {
                return this.rmsProductClass;
        }

        public final void setRmsProductClass(final Integer rmsProductClass) {
                this.rmsProductClass = rmsProductClass;
        }

        @Column(name = "PRODUCT_CLASS_NAME_ENGLISH", length = Constant.int_45)
        public final String getProductClassNameEnglish() {
                return this.productClassNameEnglish;
        }

        public final void setProductClassNameEnglish(final String productClassNameEnglish) {
                this.productClassNameEnglish = productClassNameEnglish;
        }

        @Column(name = "PRODUCT_CLASS_NAME_FRENCH", length = Constant.int_45)
        public final String getProductClassNameFrench() {
                return this.productClassNameFrench;
        }

        public final void setProductClassNameFrench(final String productClassNameFrench) {
                this.productClassNameFrench = productClassNameFrench;
        }

        @Column(name = "RMS_FINELINE_CLASS")
        public final Integer getRmsFinelineClass() {
                return this.rmsFinelineClass;
        }

        public final void setRmsFinelineClass(final Integer rmsFinelineClass) {
                this.rmsFinelineClass = rmsFinelineClass;
        }

        @Column(name = "FLC_NAME_ENGLISH", length = Constant.int_45)
        public final String getFlcNameEnglish() {
                return this.flcNameEnglish;
        }

        public final void setFlcNameEnglish(final String flcNameEnglish) {
                this.flcNameEnglish = flcNameEnglish;
        }

        @Column(name = "FLC_NAME_FRENCH", length = Constant.int_45)
        public final String getFlcNameFrench() {
                return this.flcNameFrench;
        }

        public final void setFlcNameFrench(final String flcNameFrench) {
                this.flcNameFrench = flcNameFrench;
        }

        @Column(name = "IS_PROCESS_SUCCESS", length = 1)
        public final String getIsProcessSuccess() {
                return this.isProcessSuccess;
        }

        public final void setIsProcessSuccess(final String isProcessSuccess) {
                this.isProcessSuccess = isProcessSuccess;
        }

        @Column(name = "ERROR_CODE")
        public final Integer getErrorCode() {
                return this.errorCode;
        }

        public final void setErrorCode(final Integer errorCode) {
                this.errorCode = errorCode;
        }

        @Column(name = "ERROR_DESC", length = Constant.int_65535)
        public final String getErrorDesc() {
                return this.errorDesc;
        }

        public final void setErrorDesc(final String errorDesc) {
                this.errorDesc = errorDesc;
        }

        @Column(name = "BATCH_ID", length = Constant.int_50)
        public final String getBatchId() {
                return this.batchId;
        }

        public final void setBatchId(final String batchId) {
                this.batchId = batchId;
        }

        @Column(name = "STATUS", length = Constant.int_45)
        public final String getStatus() {
                return this.status;
        }

        public final void setStatus(final String status) {
                this.status = status;
        }

        @Column(name = "CREATE_BY", length = Constant.int_50)
        public final String getCreateBy() {
                return this.createBy;
        }

        public final void setCreateBy(final String createBy) {
                this.createBy = createBy;
        }

        @Temporal(TemporalType.TIMESTAMP)
        @Column(name = "CREATE_DATE", length = Constant.int_19)
        public final Date getCreateDate() {
                return this.createDate;
        }

        public final void setCreateDate(final Date createDate) {
                this.createDate = createDate;
        }

        @Column(name = "UPDATE_BY", length = Constant.int_50)
        public final String getUpdateBy() {
                return this.updateBy;
        }

        public final void setUpdateBy(final String updateBy) {
                this.updateBy = updateBy;
        }

        @Temporal(TemporalType.TIMESTAMP)
        @Column(name = "UPDATE_DATE", length = Constant.int_19)
        public final Date getUpdateDate() {
                return this.updateDate;
        }

        public final void setUpdateDate(final Date updateDate) {
                this.updateDate = updateDate;
        }

}
