// default package
// Generated Jan 11, 2018 3:43:01 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hierarchy generated by hbm2java
 */
@Entity
@Table(name = "hierarchy", catalog = "ignitiv")
public class Hierarchy implements java.io.Serializable {

	private Integer id;
	private Integer division;
	private String divisionName;
	private String divisionNameFr;
	private Integer dept;
	private String mrkCatLevel1;
	private String mrkCatLevel1Fr;
	private Integer category;
	private String mrkCatLevel2;
	private String mrkCatLevel2Fr;
	private Integer productClass;
	private String mrkCatLevel3;
	private String mrkCatLevel3Fr;
	private Integer finelineClass;
	private String mrkCatLevel4;
	private String mrkCatLevel4Fr;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String batchId;
	private String status;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public Hierarchy() {
	}

	public Hierarchy(Integer division, String divisionName, String divisionNameFr, Integer dept, String mrkCatLevel1,
			String mrkCatLevel1Fr, Integer category, String mrkCatLevel2, String mrkCatLevel2Fr, Integer productClass,
			String mrkCatLevel3, String mrkCatLevel3Fr, Integer finelineClass, String mrkCatLevel4,
			String mrkCatLevel4Fr, String isProcessSuccess, Integer errorCode, String errorDesc, String batchId,
			String status, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.division = division;
		this.divisionName = divisionName;
		this.divisionNameFr = divisionNameFr;
		this.dept = dept;
		this.mrkCatLevel1 = mrkCatLevel1;
		this.mrkCatLevel1Fr = mrkCatLevel1Fr;
		this.category = category;
		this.mrkCatLevel2 = mrkCatLevel2;
		this.mrkCatLevel2Fr = mrkCatLevel2Fr;
		this.productClass = productClass;
		this.mrkCatLevel3 = mrkCatLevel3;
		this.mrkCatLevel3Fr = mrkCatLevel3Fr;
		this.finelineClass = finelineClass;
		this.mrkCatLevel4 = mrkCatLevel4;
		this.mrkCatLevel4Fr = mrkCatLevel4Fr;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.batchId = batchId;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DIVISION")
	public Integer getDivision() {
		return this.division;
	}

	public void setDivision(Integer division) {
		this.division = division;
	}

	@Column(name = "DIVISION_NAME", length = 45)
	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	@Column(name = "DIVISION_NAME_FR", length = 45)
	public String getDivisionNameFr() {
		return this.divisionNameFr;
	}

	public void setDivisionNameFr(String divisionNameFr) {
		this.divisionNameFr = divisionNameFr;
	}

	@Column(name = "DEPT")
	public Integer getDept() {
		return this.dept;
	}

	public void setDept(Integer dept) {
		this.dept = dept;
	}

	@Column(name = "MRK_CAT_LEVEL1", length = 45)
	public String getMrkCatLevel1() {
		return this.mrkCatLevel1;
	}

	public void setMrkCatLevel1(String mrkCatLevel1) {
		this.mrkCatLevel1 = mrkCatLevel1;
	}

	@Column(name = "MRK_CAT_LEVEL1_FR", length = 45)
	public String getMrkCatLevel1Fr() {
		return this.mrkCatLevel1Fr;
	}

	public void setMrkCatLevel1Fr(String mrkCatLevel1Fr) {
		this.mrkCatLevel1Fr = mrkCatLevel1Fr;
	}

	@Column(name = "CATEGORY")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Column(name = "MRK_CAT_LEVEL2", length = 45)
	public String getMrkCatLevel2() {
		return this.mrkCatLevel2;
	}

	public void setMrkCatLevel2(String mrkCatLevel2) {
		this.mrkCatLevel2 = mrkCatLevel2;
	}

	@Column(name = "MRK_CAT_LEVEL2_FR", length = 45)
	public String getMrkCatLevel2Fr() {
		return this.mrkCatLevel2Fr;
	}

	public void setMrkCatLevel2Fr(String mrkCatLevel2Fr) {
		this.mrkCatLevel2Fr = mrkCatLevel2Fr;
	}

	@Column(name = "PRODUCT_CLASS")
	public Integer getProductClass() {
		return this.productClass;
	}

	public void setProductClass(Integer productClass) {
		this.productClass = productClass;
	}

	@Column(name = "MRK_CAT_LEVEL3", length = 45)
	public String getMrkCatLevel3() {
		return this.mrkCatLevel3;
	}

	public void setMrkCatLevel3(String mrkCatLevel3) {
		this.mrkCatLevel3 = mrkCatLevel3;
	}

	@Column(name = "MRK_CAT_LEVEL3_FR", length = 45)
	public String getMrkCatLevel3Fr() {
		return this.mrkCatLevel3Fr;
	}

	public void setMrkCatLevel3Fr(String mrkCatLevel3Fr) {
		this.mrkCatLevel3Fr = mrkCatLevel3Fr;
	}

	@Column(name = "FINELINE_CLASS")
	public Integer getFinelineClass() {
		return this.finelineClass;
	}

	public void setFinelineClass(Integer finelineClass) {
		this.finelineClass = finelineClass;
	}

	@Column(name = "MRK_CAT_LEVEL4", length = 45)
	public String getMrkCatLevel4() {
		return this.mrkCatLevel4;
	}

	public void setMrkCatLevel4(String mrkCatLevel4) {
		this.mrkCatLevel4 = mrkCatLevel4;
	}

	@Column(name = "MRK_CAT_LEVEL4_FR", length = 45)
	public String getMrkCatLevel4Fr() {
		return this.mrkCatLevel4Fr;
	}

	public void setMrkCatLevel4Fr(String mrkCatLevel4Fr) {
		this.mrkCatLevel4Fr = mrkCatLevel4Fr;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "BATCH_ID", length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
