// default package
// Generated Nov 14, 2017 11:46:53 AM by Hibernate Tools 5.2.6.Final

package com.homehardware.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "ignitiv")
public class Item implements java.io.Serializable {

	private Integer id;
	private String item;
	private String itemDesc;
	private String hhSellingUom;
	private String sellingUomFr;
	private Integer productClass;
	private Integer category;
	private Integer finelineClass;
	private String itemDescFr;
	private String hhLumberInd;
	private String hhHardwareInd;
	private String hhFurnitureInd;
	private String hhItemSourceCode;
	private String hhWarrantyExchangeInd;
	private String comments;
	private String hhCtrlBrandInd;
	private String hhConsumerItemDesc;
	private String hhConsumerItemDescFr;
	private String ecommerceInd;
	private String brandCode;
	private String commentsFr;
	private String limitedQtyInd;
	private String displayItem;

	public Item() {
	}

	public Item(String item, String itemDesc, String hhSellingUom, String sellingUomFr, Integer productClass,
			Integer category, Integer finelineClass, String itemDescFr, String hhLumberInd, String hhHardwareInd,
			String hhFurnitureInd, String hhItemSourceCode, String hhWarrantyExchangeInd, String comments,
			String hhCtrlBrandInd, String hhConsumerItemDesc, String hhConsumerItemDescFr, String ecommerceInd,
			String brandCode, String commentsFr, String limitedQtyInd, String displayItem) {
		this.item = item;
		this.itemDesc = itemDesc;
		this.hhSellingUom = hhSellingUom;
		this.sellingUomFr = sellingUomFr;
		this.productClass = productClass;
		this.category = category;
		this.finelineClass = finelineClass;
		this.itemDescFr = itemDescFr;
		this.hhLumberInd = hhLumberInd;
		this.hhHardwareInd = hhHardwareInd;
		this.hhFurnitureInd = hhFurnitureInd;
		this.hhItemSourceCode = hhItemSourceCode;
		this.hhWarrantyExchangeInd = hhWarrantyExchangeInd;
		this.comments = comments;
		this.hhCtrlBrandInd = hhCtrlBrandInd;
		this.hhConsumerItemDesc = hhConsumerItemDesc;
		this.hhConsumerItemDescFr = hhConsumerItemDescFr;
		this.ecommerceInd = ecommerceInd;
		this.brandCode = brandCode;
		this.commentsFr = commentsFr;
		this.limitedQtyInd = limitedQtyInd;
		this.displayItem = displayItem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM", length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "ITEM_DESC", length = 65535)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "HH_SELLING_UOM", length = 100)
	public String getHhSellingUom() {
		return this.hhSellingUom;
	}

	public void setHhSellingUom(String hhSellingUom) {
		this.hhSellingUom = hhSellingUom;
	}

	@Column(name = "SELLING_UOM_FR", length = 100)
	public String getSellingUomFr() {
		return this.sellingUomFr;
	}

	public void setSellingUomFr(String sellingUomFr) {
		this.sellingUomFr = sellingUomFr;
	}

	@Column(name = "PRODUCT_CLASS")
	public Integer getProductClass() {
		return this.productClass;
	}

	public void setProductClass(Integer productClass) {
		this.productClass = productClass;
	}

	@Column(name = "CATEGORY")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Column(name = "FINELINE_CLASS")
	public Integer getFinelineClass() {
		return this.finelineClass;
	}

	public void setFinelineClass(Integer finelineClass) {
		this.finelineClass = finelineClass;
	}

	@Column(name = "ITEM_DESC_FR", length = 65535)
	public String getItemDescFr() {
		return this.itemDescFr;
	}

	public void setItemDescFr(String itemDescFr) {
		this.itemDescFr = itemDescFr;
	}

	@Column(name = "HH_LUMBER_IND", length = 1)
	public String getHhLumberInd() {
		return this.hhLumberInd;
	}

	public void setHhLumberInd(String hhLumberInd) {
		this.hhLumberInd = hhLumberInd;
	}

	@Column(name = "HH_HARDWARE_IND", length = 1)
	public String getHhHardwareInd() {
		return this.hhHardwareInd;
	}

	public void setHhHardwareInd(String hhHardwareInd) {
		this.hhHardwareInd = hhHardwareInd;
	}

	@Column(name = "HH_FURNITURE_IND", length = 1)
	public String getHhFurnitureInd() {
		return this.hhFurnitureInd;
	}

	public void setHhFurnitureInd(String hhFurnitureInd) {
		this.hhFurnitureInd = hhFurnitureInd;
	}

	@Column(name = "HH_ITEM_SOURCE_CODE", length = 1)
	public String getHhItemSourceCode() {
		return this.hhItemSourceCode;
	}

	public void setHhItemSourceCode(String hhItemSourceCode) {
		this.hhItemSourceCode = hhItemSourceCode;
	}

	@Column(name = "HH_WARRANTY_EXCHANGE_IND", length = 1)
	public String getHhWarrantyExchangeInd() {
		return this.hhWarrantyExchangeInd;
	}

	public void setHhWarrantyExchangeInd(String hhWarrantyExchangeInd) {
		this.hhWarrantyExchangeInd = hhWarrantyExchangeInd;
	}

	@Column(name = "COMMENTS", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "HH_CTRL_BRAND_IND", length = 1)
	public String getHhCtrlBrandInd() {
		return this.hhCtrlBrandInd;
	}

	public void setHhCtrlBrandInd(String hhCtrlBrandInd) {
		this.hhCtrlBrandInd = hhCtrlBrandInd;
	}

	@Column(name = "HH_CONSUMER_ITEM_DESC", length = 65535)
	public String getHhConsumerItemDesc() {
		return this.hhConsumerItemDesc;
	}

	public void setHhConsumerItemDesc(String hhConsumerItemDesc) {
		this.hhConsumerItemDesc = hhConsumerItemDesc;
	}

	@Column(name = "HH_CONSUMER_ITEM_DESC_FR", length = 65535)
	public String getHhConsumerItemDescFr() {
		return this.hhConsumerItemDescFr;
	}

	public void setHhConsumerItemDescFr(String hhConsumerItemDescFr) {
		this.hhConsumerItemDescFr = hhConsumerItemDescFr;
	}

	@Column(name = "ECOMMERCE_IND", length = 1)
	public String getEcommerceInd() {
		return this.ecommerceInd;
	}

	public void setEcommerceInd(String ecommerceInd) {
		this.ecommerceInd = ecommerceInd;
	}

	@Column(name = "BRAND_CODE", length = 64)
	public String getBrandCode() {
		return this.brandCode;
	}

	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	@Column(name = "COMMENTS_FR", length = 65535)
	public String getCommentsFr() {
		return this.commentsFr;
	}

	public void setCommentsFr(String commentsFr) {
		this.commentsFr = commentsFr;
	}

	@Column(name = "LIMITED_QTY_IND", length = 1)
	public String getLimitedQtyInd() {
		return this.limitedQtyInd;
	}

	public void setLimitedQtyInd(String limitedQtyInd) {
		this.limitedQtyInd = limitedQtyInd;
	}

	@Column(name = "DISPLAY_ITEM", length = 100)
	public String getDisplayItem() {
		return this.displayItem;
	}

	public void setDisplayItem(String displayItem) {
		this.displayItem = displayItem;
	}

}
