// default package
// Generated Nov 29, 2017 10:39:48 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "ignitiv")
public class Item implements java.io.Serializable {

	private ItemId id;
	private String itemDesc;
	private String hhSellingUom;
	private String sellingUomFr;
	private Integer productClass;
	private Integer category;
	private Integer finelineClass;
	private String itemDescFr;
	private String brandDesc;
	private String codeDesc;
	private String hhExclusiveToHomeInd;
	private String hhRetailResponsibilityCode;
	private String hhLumberInd;
	private String hhHardwareInd;
	private String hhFurnitureInd;
	private String hhEnergyStarInd;
	private String hhItemSourceCode;
	private String hhHomeExpressionsInd;
	private String hhWarrantyExchangeInd;
	private String comments;
	private String hhCtrlBrandInd;
	private String hhConsumerItemDesc;
	private String hhConsumerItemDescFr;
	private String gstInd;
	private String ecommerceInd;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String status;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	
	
	

	public Item() {
	}

	public Item(ItemId id) {
		this.id = id;
	}

	public Item(ItemId id, String itemDesc, String hhSellingUom, String sellingUomFr, Integer productClass,
			Integer category, Integer finelineClass, String itemDescFr, String brandDesc, String codeDesc,
			String hhExclusiveToHomeInd, String hhRetailResponsibilityCode, String hhLumberInd, String hhHardwareInd,
			String hhFurnitureInd, String hhEnergyStarInd, String hhItemSourceCode, String hhHomeExpressionsInd,
			String hhWarrantyExchangeInd, String comments, String hhCtrlBrandInd, String hhConsumerItemDesc,
			String hhConsumerItemDescFr, String gstInd, String ecommerceInd, String isProcessSuccess, Integer errorCode,
			String errorDesc, String status, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.id = id;
		this.itemDesc = itemDesc;
		this.hhSellingUom = hhSellingUom;
		this.sellingUomFr = sellingUomFr;
		this.productClass = productClass;
		this.category = category;
		this.finelineClass = finelineClass;
		this.itemDescFr = itemDescFr;
		this.brandDesc = brandDesc;
		this.codeDesc = codeDesc;
		this.hhExclusiveToHomeInd = hhExclusiveToHomeInd;
		this.hhRetailResponsibilityCode = hhRetailResponsibilityCode;
		this.hhLumberInd = hhLumberInd;
		this.hhHardwareInd = hhHardwareInd;
		this.hhFurnitureInd = hhFurnitureInd;
		this.hhEnergyStarInd = hhEnergyStarInd;
		this.hhItemSourceCode = hhItemSourceCode;
		this.hhHomeExpressionsInd = hhHomeExpressionsInd;
		this.hhWarrantyExchangeInd = hhWarrantyExchangeInd;
		this.comments = comments;
		this.hhCtrlBrandInd = hhCtrlBrandInd;
		this.hhConsumerItemDesc = hhConsumerItemDesc;
		this.hhConsumerItemDescFr = hhConsumerItemDescFr;
		this.gstInd = gstInd;
		this.ecommerceInd = ecommerceInd;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "item", column = @Column(name = "ITEM", nullable = false, length = 45)),
			@AttributeOverride(name = "batchId", column = @Column(name = "BATCH_ID", nullable = false, length = 50)) })
	public ItemId getId() {
		return this.id;
	}

	public void setId(ItemId id) {
		this.id = id;
	}

	@Column(name = "ITEM_DESC", length = 100)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "HH_SELLING_UOM", length = 45)
	public String getHhSellingUom() {
		return this.hhSellingUom;
	}

	public void setHhSellingUom(String hhSellingUom) {
		this.hhSellingUom = hhSellingUom;
	}

	@Column(name = "SELLING_UOM_FR", length = 45)
	public String getSellingUomFr() {
		return this.sellingUomFr;
	}

	public void setSellingUomFr(String sellingUomFr) {
		this.sellingUomFr = sellingUomFr;
	}

	@Column(name = "PRODUCT_CLASS")
	public Integer getProductClass() {
		return this.productClass;
	}

	public void setProductClass(Integer productClass) {
		this.productClass = productClass;
	}

	@Column(name = "CATEGORY")
	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	@Column(name = "FINELINE_CLASS")
	public Integer getFinelineClass() {
		return this.finelineClass;
	}

	public void setFinelineClass(Integer finelineClass) {
		this.finelineClass = finelineClass;
	}

	@Column(name = "ITEM_DESC_FR", length = 45)
	public String getItemDescFr() {
		return this.itemDescFr;
	}

	public void setItemDescFr(String itemDescFr) {
		this.itemDescFr = itemDescFr;
	}

	@Column(name = "BRAND_DESC", length = 45)
	public String getBrandDesc() {
		return this.brandDesc;
	}

	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc;
	}

	@Column(name = "CODE_DESC", length = 45)
	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	@Column(name = "HH_EXCLUSIVE_TO_HOME_IND", length = 1)
	public String getHhExclusiveToHomeInd() {
		return this.hhExclusiveToHomeInd;
	}

	public void setHhExclusiveToHomeInd(String hhExclusiveToHomeInd) {
		this.hhExclusiveToHomeInd = hhExclusiveToHomeInd;
	}

	@Column(name = "HH_RETAIL_RESPONSIBILITY_CODE", length = 1)
	public String getHhRetailResponsibilityCode() {
		return this.hhRetailResponsibilityCode;
	}

	public void setHhRetailResponsibilityCode(String hhRetailResponsibilityCode) {
		this.hhRetailResponsibilityCode = hhRetailResponsibilityCode;
	}

	@Column(name = "HH_LUMBER_IND", length = 1)
	public String getHhLumberInd() {
		return this.hhLumberInd;
	}

	public void setHhLumberInd(String hhLumberInd) {
		this.hhLumberInd = hhLumberInd;
	}

	@Column(name = "HH_HARDWARE_IND", length = 1)
	public String getHhHardwareInd() {
		return this.hhHardwareInd;
	}

	public void setHhHardwareInd(String hhHardwareInd) {
		this.hhHardwareInd = hhHardwareInd;
	}

	@Column(name = "HH_FURNITURE_IND", length = 1)
	public String getHhFurnitureInd() {
		return this.hhFurnitureInd;
	}

	public void setHhFurnitureInd(String hhFurnitureInd) {
		this.hhFurnitureInd = hhFurnitureInd;
	}

	@Column(name = "HH_ENERGY_STAR_IND", length = 1)
	public String getHhEnergyStarInd() {
		return this.hhEnergyStarInd;
	}

	public void setHhEnergyStarInd(String hhEnergyStarInd) {
		this.hhEnergyStarInd = hhEnergyStarInd;
	}

	@Column(name = "HH_ITEM_SOURCE_CODE", length = 1)
	public String getHhItemSourceCode() {
		return this.hhItemSourceCode;
	}

	public void setHhItemSourceCode(String hhItemSourceCode) {
		this.hhItemSourceCode = hhItemSourceCode;
	}

	@Column(name = "HH_HOME_EXPRESSIONS_IND", length = 1)
	public String getHhHomeExpressionsInd() {
		return this.hhHomeExpressionsInd;
	}

	public void setHhHomeExpressionsInd(String hhHomeExpressionsInd) {
		this.hhHomeExpressionsInd = hhHomeExpressionsInd;
	}

	@Column(name = "HH_WARRANTY_EXCHANGE_IND", length = 1)
	public String getHhWarrantyExchangeInd() {
		return this.hhWarrantyExchangeInd;
	}

	public void setHhWarrantyExchangeInd(String hhWarrantyExchangeInd) {
		this.hhWarrantyExchangeInd = hhWarrantyExchangeInd;
	}

	@Column(name = "COMMENTS", length = 100)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "HH_CTRL_BRAND_IND", length = 1)
	public String getHhCtrlBrandInd() {
		return this.hhCtrlBrandInd;
	}

	public void setHhCtrlBrandInd(String hhCtrlBrandInd) {
		this.hhCtrlBrandInd = hhCtrlBrandInd;
	}

	@Column(name = "HH_CONSUMER_ITEM_DESC", length = 100)
	public String getHhConsumerItemDesc() {
		return this.hhConsumerItemDesc;
	}

	public void setHhConsumerItemDesc(String hhConsumerItemDesc) {
		this.hhConsumerItemDesc = hhConsumerItemDesc;
	}

	@Column(name = "HH_CONSUMER_ITEM_DESC_FR", length = 100)
	public String getHhConsumerItemDescFr() {
		return this.hhConsumerItemDescFr;
	}

	public void setHhConsumerItemDescFr(String hhConsumerItemDescFr) {
		this.hhConsumerItemDescFr = hhConsumerItemDescFr;
	}

	@Column(name = "GST_IND", length = 1)
	public String getGstInd() {
		return this.gstInd;
	}

	public void setGstInd(String gstInd) {
		this.gstInd = gstInd;
	}

	@Column(name = "ECOMMERCE_IND", length = 1)
	public String getEcommerceInd() {
		return this.ecommerceInd;
	}

	public void setEcommerceInd(String ecommerceInd) {
		this.ecommerceInd = ecommerceInd;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	private List<ExtDesc> extDesc;
	
	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
         @JoinColumn(name="ITEM", referencedColumnName = "ITEM"),
         @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
         })
	public List<ExtDesc> getExtDesc() {
		return extDesc;
	}

	public void setExtDesc(List<ExtDesc> extDesc) {
		this.extDesc = extDesc;
	}
	
	private List<ItemDynAttr> itemDynAttr;

	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
        @JoinColumn(name="ITEM", referencedColumnName = "ITEM"),
        @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
        })
	public List<ItemDynAttr> getItemDynAttr() {
		return itemDynAttr;
	}

	public void setItemDynAttr(List<ItemDynAttr> itemDynAttr) {
		this.itemDynAttr = itemDynAttr;
	}
	
	private List<Promotion> promotion;
	

	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
        @JoinColumn(name="D_ITEM", referencedColumnName = "ITEM"),
        @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
        })
	public List<Promotion> getPromotion() {
		return promotion;
	}

	public void setPromotion(List<Promotion> promotion) {
		this.promotion = promotion;
	}

	private List<RetailMsrp> retailMsrp;
	

	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
        @JoinColumn(name="ITEM", referencedColumnName = "ITEM"),
        @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
        })
	public List<RetailMsrp> getRetailMsrp() {
		return retailMsrp;
	}

	public void setRetailMsrp(List<RetailMsrp> retailMsrp) {
		this.retailMsrp = retailMsrp;
	}
	
	private List<ItemInventory> itemInventory;
	
	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
       @JoinColumn(name="ITEM", referencedColumnName = "ITEM"),
       @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
       })
	public List<ItemInventory> getItemInventory() {
		return itemInventory;
	}

	public void setItemInventory(List<ItemInventory> itemInventory) {
		this.itemInventory = itemInventory;
	}

	
	private List<ItemLoc> itemLoc;
	
	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
	 @JoinColumns({
      @JoinColumn(name="ITEM", referencedColumnName = "ITEM"),
      @JoinColumn(name="BATCH_ID", referencedColumnName = "BATCH_ID")
      })
	public List<ItemLoc> getItemLoc() {
		return itemLoc;
	}

	public void setItemLoc(List<ItemLoc> itemLoc) {
		this.itemLoc = itemLoc;
	}

	public String toString(){
		String returnToString= " Item Id : "+this.getId().getItem() + " : batch Id : "+this.getId().getBatchId()+" \n ";
		if(this.itemDynAttr!=null&& this.itemDynAttr.size()!=0){
		for(ItemDynAttr id :this.getItemDynAttr()){
			returnToString +=id; 
		}
		}
		if(this.extDesc!=null && this.extDesc.size()!=0){
			for(ExtDesc id :this.getExtDesc()){
				returnToString +=id; 
			}
			}
		if(this.retailMsrp!=null && this.retailMsrp.size()!=0){
			for(RetailMsrp id :this.getRetailMsrp()){
				returnToString +=id; 
			}
			}
		if(this.promotion!=null && this.promotion.size()!=0){
			for(Promotion id :this.getPromotion()){
				returnToString +=id; 
			}
			}
		if(this.itemLoc!=null && this.itemLoc.size()!=0){
			for(ItemLoc id :this.getItemLoc()){
				returnToString +=id; 
			}
			}
		if(this.itemInventory!=null && this.itemInventory.size()!=0){
			for(ItemInventory id :this.getItemInventory()){
				returnToString +=id; 
			}
			}
		returnToString+="\n";
		return returnToString;
	}
}
