// default package
// Generated Dec 1, 2017 5:12:24 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemRestricted generated by hbm2java
 */
@Entity
@Table(name = "item_restricted", catalog = "ignitiv")
public class ItemRestricted implements java.io.Serializable {

	private Integer id;
	private String item;
	private Integer store;
	private String websiteInd;
	private String ecommerceInd;
	private String prov;
	private String shipToHomeInd;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;

	public ItemRestricted() {
	}

	public ItemRestricted(String websiteInd, String shipToHomeInd) {
		this.websiteInd = websiteInd;
		this.shipToHomeInd = shipToHomeInd;
	}

	public ItemRestricted(String item, Integer store, String websiteInd, String ecommerceInd, String prov,
			String shipToHomeInd, String isProcessSuccess, Integer errorCode, String errorDesc) {
		this.item = item;
		this.store = store;
		this.websiteInd = websiteInd;
		this.ecommerceInd = ecommerceInd;
		this.prov = prov;
		this.shipToHomeInd = shipToHomeInd;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM", length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "STORE")
	public Integer getStore() {
		return this.store;
	}

	public void setStore(Integer store) {
		this.store = store;
	}

	@Column(name = "WEBSITE_IND", nullable = false, length = 1)
	public String getWebsiteInd() {
		return this.websiteInd;
	}

	public void setWebsiteInd(String websiteInd) {
		this.websiteInd = websiteInd;
	}

	@Column(name = "ECOMMERCE_IND", length = 1)
	public String getEcommerceInd() {
		return this.ecommerceInd;
	}

	public void setEcommerceInd(String ecommerceInd) {
		this.ecommerceInd = ecommerceInd;
	}

	@Column(name = "PROV", length = 64)
	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	@Column(name = "SHIP_TO_HOME_IND", nullable = false, length = 1)
	public String getShipToHomeInd() {
		return this.shipToHomeInd;
	}

	public void setShipToHomeInd(String shipToHomeInd) {
		this.shipToHomeInd = shipToHomeInd;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

}
