package com.homehardware.model;
// Generated Nov 1, 2017 12:57:35 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemDynAttrId generated by hbm2java.
 */
@Embeddable
@Entity
@Table(name = "item_dyn_attr")
public final class ItemDynAttrId implements java.io.Serializable {

	@Column(name = "ITEM")
	private String item;
	
	@Column(name = "DYN_ATTR_DESC")
	private String dynAttrDesc;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID")
	private Integer id;

	
	public Integer getId() {
		return id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public ItemDynAttrId() {
	}

	public ItemDynAttrId(final String item, final String dynAttrDesc) {
		this.item = item;
		this.dynAttrDesc = dynAttrDesc;
	}

	/*@Column(name = "ITEM", length = 10)*/
	public String getItem() {
		return this.item;
	}

	public void setItem(final String item) {
		this.item = item;
	}

	/*@Column(name = "DYN_ATTR_DESC", length = 100)*/
	public String getDynAttrDesc() {
		return this.dynAttrDesc;
	}

	public void setDynAttrDesc(final String dynAttrDesc) {
		this.dynAttrDesc = dynAttrDesc;
	}

	
}
