package com.homehardware.model;
// Generated Oct 30, 2017 11:27:55 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Embeddable;

/**
 * ItemDynAttr generated by hbm2java.
 */
@Embeddable
public final class ItemDynAttr implements java.io.Serializable {

	String item;
	String dynAttrDesc;

	
	public ItemDynAttr() {
	}


	public final String getItem() {
		return  item;
	}


	public final void setItem(final String item) {
		this.item = item;
	}


	public final String getDynAttrDesc() {
		return dynAttrDesc;
	}


	public final void setDynAttrDesc(final String dynAttrDesc) {
		this.dynAttrDesc = dynAttrDesc;
	}

	

	

	

}
