// default package
// Generated Nov 14, 2017 11:46:53 AM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemDynAttr generated by hbm2java
 */
@Entity
@Table(name = "item_dyn_attr", catalog = "ignitiv")
public class ItemDynAttr implements java.io.Serializable {

	private Integer id;
	private String item;
	private String dynAttrDesc;

	public ItemDynAttr() {
	}

	public ItemDynAttr(String item, String dynAttrDesc) {
		this.item = item;
		this.dynAttrDesc = dynAttrDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ITEM", length = 10)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "DYN_ATTR_DESC", length = 100)
	public String getDynAttrDesc() {
		return this.dynAttrDesc;
	}

	public void setDynAttrDesc(String dynAttrDesc) {
		this.dynAttrDesc = dynAttrDesc;
	}

}
