// default package
// Generated Nov 29, 2017 10:39:48 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;

/**
 * ItemId generated by hbm2java
 */
@Embeddable
public class ItemId implements java.io.Serializable {

	private String item;
	private String batchId;

	public ItemId() {
	}

	public ItemId(String item, String batchId) {
		this.item = item;
		this.batchId = batchId;
	}

	@Column(name = "ITEM", nullable = false, length = 45)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "BATCH_ID", nullable = false, length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}
	


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemId))
			return false;
		ItemId castOther = (ItemId) other;

		return ((this.getItem() == castOther.getItem()) || (this.getItem() != null && castOther.getItem() != null
				&& this.getItem().equals(castOther.getItem())))
				&& ((this.getBatchId() == castOther.getBatchId()) || (this.getBatchId() != null
						&& castOther.getBatchId() != null && this.getBatchId().equals(castOther.getBatchId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItem() == null ? 0 : this.getItem().hashCode());
		result = 37 * result + (getBatchId() == null ? 0 : this.getBatchId().hashCode());
		return result;
	}

}
