// default package
// Generated Dec 27, 2017 12:53:18 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductItemAttributes generated by hbm2java
 */
@Entity
@Table(name = "product_item_attributes", catalog = "ignitiv")
public class ProductItemAttributes implements java.io.Serializable {

	private ProductItemAttributesId id;
	private Integer jobId;
	private String attributeValue;
	private String attributeValueFr;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String status;
	private String batchId;

	public ProductItemAttributes() {
	}

	public ProductItemAttributes(ProductItemAttributesId id) {
		this.id = id;
	}

	public ProductItemAttributes(ProductItemAttributesId id, Integer jobId, String attributeValue,
			String attributeValueFr, String isProcessSuccess, Integer errorCode, String errorDesc, String status,
			String batchId) {
		this.id = id;
		this.jobId = jobId;
		this.attributeValue = attributeValue;
		this.attributeValueFr = attributeValueFr;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.status = status;
		this.batchId = batchId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productAttrId", column = @Column(name = "PRODUCT_ATTR_ID", nullable = false, length = 64)),
			@AttributeOverride(name = "item", column = @Column(name = "ITEM", nullable = false, length = 64)) })
	public ProductItemAttributesId getId() {
		return this.id;
	}

	public void setId(ProductItemAttributesId id) {
		this.id = id;
	}

	@Column(name = "JOB_ID")
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "ATTRIBUTE_VALUE", length = 64)
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Column(name = "ATTRIBUTE_VALUE_FR", length = 64)
	public String getAttributeValueFr() {
		return this.attributeValueFr;
	}

	public void setAttributeValueFr(String attributeValueFr) {
		this.attributeValueFr = attributeValueFr;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "status", length = 64)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "BATCH_ID", length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

}
