package com.homehardware.model;
// Generated Nov 14, 2017 11:53:36 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute", catalog = "ignitiv")
public class ProductAttribute implements java.io.Serializable {

	private String productAttrId;
	private Integer jobId;
	private String attributeName;
	private String attributeNameFr;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;

	public ProductAttribute() {
	}

	public ProductAttribute(String productAttrId) {
		this.productAttrId = productAttrId;
	}

	public ProductAttribute(String productAttrId, Integer jobId, String attributeName, String attributeNameFr,
			String isProcessSuccess, Integer errorCode, String errorDesc) {
		this.productAttrId = productAttrId;
		this.jobId = jobId;
		this.attributeName = attributeName;
		this.attributeNameFr = attributeNameFr;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
	}

	@Id

	@Column(name = "PRODUCT_ATTR_ID", unique = true, nullable = false, length = 64)
	public String getProductAttrId() {
		return this.productAttrId;
	}

	public void setProductAttrId(String productAttrId) {
		this.productAttrId = productAttrId;
	}

	@Column(name = "JOB_ID")
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "ATTRIBUTE_NAME", length = 64)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_NAME_FR", length = 64)
	public String getAttributeNameFr() {
		return this.attributeNameFr;
	}

	public void setAttributeNameFr(String attributeNameFr) {
		this.attributeNameFr = attributeNameFr;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

}
