// default package
// Generated Nov 20, 2017 3:39:29 PM by Hibernate Tools 5.2.6.Final

package com.homehardware.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.hh.integration.constants.Constant;

/**.
 * ProductItemAttributes generated by hbm2java
 */
@Entity
@Table(name = "product_item_attributes", catalog = "ignitiv")
public class ProductItemAttributes implements java.io.Serializable {

	
	
	private ProductItemAttributesId id;
	private Integer jobId;
	private String attributeValue;
	private String attributeValueFr;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String status;

	public ProductItemAttributes() {
	}

	public ProductItemAttributes(final ProductItemAttributesId id) {
		this.id = id;
	}

	/**
	 * @param id.
	 * @param jobId.
	 * @param attributeValue.
	 * @param attributeValueFr.
	 * @param isProcessSuccess.
	 * @param errorCode.
	 * @param errorDesc.
	 * @param status.
	 */
	public ProductItemAttributes(
			final ProductItemAttributesId id, 
			final Integer jobId, final String attributeValue,
			final String attributeValueFr, 
			final String isProcessSuccess, 
			final Integer errorCode, final String errorDesc, final String status) {
		this.id = id;
		this.jobId = jobId;
		this.attributeValue = attributeValue;
		this.attributeValueFr = attributeValueFr;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productAttrId",
					column = @Column(
							name = "PRODUCT_ATTR_ID",
							nullable = false, 
							length = Constant.int_64)),
			@AttributeOverride(
					name = "item", 
					column = 
					@Column(name = "ITEM",
					nullable = false, length = Constant.int_64)) })
	public final ProductItemAttributesId getId() {
		return this.id;
	}

	public final void setId(final ProductItemAttributesId id) {
		this.id = id;
	}

	@Column(name = "JOB_ID")
	public final Integer getJobId() {
		return this.jobId;
	}

	public final void setJobId(final Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "ATTRIBUTE_VALUE", length = Constant.int_64)
	public final String getAttributeValue() {
		return this.attributeValue;
	}

	public final void setAttributeValue(final String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Column(name = "ATTRIBUTE_VALUE_FR", length = Constant.int_64)
	public final String getAttributeValueFr() {
		return this.attributeValueFr;
	}

	public final void setAttributeValueFr(final String attributeValueFr) {
		this.attributeValueFr = attributeValueFr;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public final String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public final void setIsProcessSuccess(final String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public final Integer getErrorCode() {
		return this.errorCode;
	}

	public final void setErrorCode(final Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = Constant.int_65535)
	public final String getErrorDesc() {
		return this.errorDesc;
	}

	public final void setErrorDesc(final String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "status", length = Constant.int_64)
	public final String getStatus() {
		return this.status;
	}

	public final void setStatus(final String status) {
		this.status = status;
	}

}
