// default package
// Generated Nov 14, 2017 4:09:32 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductItemAttributesId generated by hbm2java
 */
@Embeddable
public class ProductItemAttributesId implements java.io.Serializable {

	private String productAttrId;
	private String item;

	public ProductItemAttributesId() {
	}

	public ProductItemAttributesId(String productAttrId, String item) {
		this.productAttrId = productAttrId;
		this.item = item;
	}

	@Column(name = "PRODUCT_ATTR_ID", nullable = false, length = 64)
	public String getProductAttrId() {
		return this.productAttrId;
	}

	public void setProductAttrId(String productAttrId) {
		this.productAttrId = productAttrId;
	}

	@Column(name = "ITEM", nullable = false, length = 64)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductItemAttributesId))
			return false;
		ProductItemAttributesId castOther = (ProductItemAttributesId) other;

		return ((this.getProductAttrId() == castOther.getProductAttrId())
				|| (this.getProductAttrId() != null && castOther.getProductAttrId() != null
						&& this.getProductAttrId().equals(castOther.getProductAttrId())))
				&& ((this.getItem() == castOther.getItem()) || (this.getItem() != null && castOther.getItem() != null
						&& this.getItem().equals(castOther.getItem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductAttrId() == null ? 0 : this.getProductAttrId().hashCode());
		result = 37 * result + (getItem() == null ? 0 : this.getItem().hashCode());
		return result;
	}

}
