package com.homehardware.model;
// Generated Nov 14, 2017 11:53:36 AM by Hibernate Tools 5.2.6.Final

import com.hh.integration.constants.Constant;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;



/**.
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute", catalog = "ignitiv")
public final class ProductAttribute implements java.io.Serializable {

	private String productAttrId;
	private Integer jobId;
	private String attributeName;
	private String attributeNameFr;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;

	public ProductAttribute() {
	}

	public ProductAttribute(final String productAttrId) {
		this.productAttrId = productAttrId;
	}

	public ProductAttribute(final String productAttrId,
			final Integer jobId, final String attributeName,
			final String attributeNameFr,
			final String isProcessSuccess, final Integer errorCode,
			final String errorDesc) {
		this.productAttrId = productAttrId;
		this.jobId = jobId;
		this.attributeName = attributeName;
		this.attributeNameFr = attributeNameFr;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
	}

	@Id
	@Column(name = "PRODUCT_ATTR_ID", unique = true, nullable = false, length = Constant.int_64)
	public final String getProductAttrId() {
		return this.productAttrId;
	}

	public final void setProductAttrId(final String productAttrId) {
		this.productAttrId = productAttrId;
	}

	@Column(name = "JOB_ID")
	public final Integer getJobId() {
		return this.jobId;
	}

	public final void setJobId(final Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "ATTRIBUTE_NAME", length = Constant.int_64)
	public final String getAttributeName() {
		return this.attributeName;
	}

	public final void setAttributeName(final String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_NAME_FR", length = Constant.int_64)
	public final String getAttributeNameFr() {
		return this.attributeNameFr;
	}

	public final void setAttributeNameFr(final String attributeNameFr) {
		this.attributeNameFr = attributeNameFr;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public final String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public final void setIsProcessSuccess(final String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public final Integer getErrorCode() {
		return this.errorCode;
	}

	public final void setErrorCode(final Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public final String getErrorDesc() {
		return this.errorDesc;
	}

	public final void setErrorDesc(final String errorDesc) {
		this.errorDesc = errorDesc;
	}

}
