// default package
// Generated Nov 29, 2017 3:10:59 PM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "ignitiv")
public class Promotion implements java.io.Serializable {

	private Integer id;
	private Date startDate;
	private Date endDate;
	private String DCodeDesc;
	private String DItem;
	private String homeCardFinanceInd;
	private String couponType;
	private BigDecimal promoRetail;
	private BigDecimal marketingRetail;
	private int store;
	private String promoItemType;
	private String isProcessSuccess;
	private Integer errorCode;
	private String errorDesc;
	private String batchId;
	private String status;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public Promotion() {
	}

	public Promotion(Date startDate, Date endDate, int store) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.store = store;
	}

	public Promotion(Date startDate, Date endDate, String DCodeDesc, String DItem, String homeCardFinanceInd,
			String couponType, BigDecimal promoRetail, BigDecimal marketingRetail, int store, String promoItemType,
			String isProcessSuccess, Integer errorCode, String errorDesc, String batchId, String status,
			String createBy, Date createDate, String updateBy, Date updateDate) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.DCodeDesc = DCodeDesc;
		this.DItem = DItem;
		this.homeCardFinanceInd = homeCardFinanceInd;
		this.couponType = couponType;
		this.promoRetail = promoRetail;
		this.marketingRetail = marketingRetail;
		this.store = store;
		this.promoItemType = promoItemType;
		this.isProcessSuccess = isProcessSuccess;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.batchId = batchId;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "D_CODE_DESC", length = 65535)
	public String getDCodeDesc() {
		return this.DCodeDesc;
	}

	public void setDCodeDesc(String DCodeDesc) {
		this.DCodeDesc = DCodeDesc;
	}

	@Column(name = "D_ITEM", length = 64)
	public String getDItem() {
		return this.DItem;
	}

	public void setDItem(String DItem) {
		this.DItem = DItem;
	}

	@Column(name = "HOME_CARD_FINANCE_IND", length = 1)
	public String getHomeCardFinanceInd() {
		return this.homeCardFinanceInd;
	}

	public void setHomeCardFinanceInd(String homeCardFinanceInd) {
		this.homeCardFinanceInd = homeCardFinanceInd;
	}

	@Column(name = "COUPON_TYPE", length = 45)
	public String getCouponType() {
		return this.couponType;
	}

	public void setCouponType(String couponType) {
		this.couponType = couponType;
	}

	@Column(name = "PROMO_RETAIL", precision = 10)
	public BigDecimal getPromoRetail() {
		return this.promoRetail;
	}

	public void setPromoRetail(BigDecimal promoRetail) {
		this.promoRetail = promoRetail;
	}

	@Column(name = "MARKETING_RETAIL", precision = 10)
	public BigDecimal getMarketingRetail() {
		return this.marketingRetail;
	}

	public void setMarketingRetail(BigDecimal marketingRetail) {
		this.marketingRetail = marketingRetail;
	}

	@Column(name = "STORE", nullable = false)
	public int getStore() {
		return this.store;
	}

	public void setStore(int store) {
		this.store = store;
	}

	@Column(name = "PROMO_ITEM_TYPE", length = 11)
	public String getPromoItemType() {
		return this.promoItemType;
	}

	public void setPromoItemType(String promoItemType) {
		this.promoItemType = promoItemType;
	}

	@Column(name = "IS_PROCESS_SUCCESS", length = 1)
	public String getIsProcessSuccess() {
		return this.isProcessSuccess;
	}

	public void setIsProcessSuccess(String isProcessSuccess) {
		this.isProcessSuccess = isProcessSuccess;
	}

	@Column(name = "ERROR_CODE")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_DESC", length = 65535)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "BATCH_ID", length = 50)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	
	public String toString(){
		return "Promotion Details DCodeDesc : "+DCodeDesc+" : Promo Retails : "+promoRetail+" : marketingRetail : " +marketingRetail+ " : batch id : "+batchId+" : store : "+store+" \n ";
	}

}
