package com.homehardware.model;
// Generated Nov 27, 2017 6:04:47 PM by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import com.hh.integration.constants.Constant;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.camel.dataformat.bindy.annotation.CsvRecord;
import org.apache.camel.dataformat.bindy.annotation.DataField;

/**
 * Promotion generated by hbm2java.
 */
@Entity
@Table(name = "promotion", catalog = "ignitiv")
@CsvRecord(separator = "\\|", skipFirstLine = true)
public class Promotion implements java.io.Serializable {

        private static final long serialVersionUID = 1L;
        private Integer id;
        @DataField(pos = Constant.int_1)
        private String startDate;
        @DataField(pos = Constant.int_2)
        private String endDate;
        @DataField(pos = Constant.int_3)
        private String DCodeDesc;
        @DataField(pos = Constant.int_4)
        private String DItem;
        @DataField(pos = Constant.int_5)
        private String homeCardFinanceInd;
        @DataField(pos = Constant.int_6)
        private String couponType;
        @DataField(pos = Constant.int_7)
        private Double promoRetail;
        @DataField(pos = Constant.int_8)
        private Double marketingRetail;
        @DataField(pos = Constant.int_9)
        private int store;
        @DataField(pos = Constant.int_10)
        private String promoItemType;
        private String isProcessSuccess;
        private Integer errorCode;
        private String errorDesc;
        private String batchId;
        private String status;
        private String createBy;
        private Date createDate;
        private String updateBy;
        private Date updateDate;

        public Promotion() {
        }

        public Promotion(final String startDate, final String endDate, final String DCodeDesc,
                        final String DItem, final String homeCardFinanceInd,
                        final String couponType, final Double promoRetail,
                        final Double marketingRetail, final int store, final String promoItemType,
                        final String isProcessSuccess, final Integer errorCode,
                        final String errorDesc, final String batchId, final String status,
                        final String createBy, final Date createDate, final String updateBy,
                        final Date updateDate) {
                this.startDate = startDate;
                this.endDate = endDate;
                this.DCodeDesc = DCodeDesc;
                this.DItem = DItem;
                this.homeCardFinanceInd = homeCardFinanceInd;
                this.couponType = couponType;
                this.promoRetail = promoRetail;
                this.marketingRetail = marketingRetail;
                this.store = store;
                this.promoItemType = promoItemType;
                this.isProcessSuccess = isProcessSuccess;
                this.errorCode = errorCode;
                this.errorDesc = errorDesc;
                this.batchId = batchId;
                this.status = status;
                this.createBy = createBy;
                this.createDate = createDate;
                this.updateBy = updateBy;
                this.updateDate = updateDate;
        }

        @Id
        @GeneratedValue(strategy = IDENTITY)
        @Column(name = "id", unique = true, nullable = false)
        public final Integer getId() {
                return this.id;
        }

        public final void setId(final Integer id) {
                this.id = id;
        }

        // @Temporal(TemporalType.DATE)
        @Column(name = "START_DATE", nullable = false, length = Constant.int_10)
        public final String getStartDate() {
                return this.startDate;
        }

        public final void setStartDate(final String startDate) {
                this.startDate = startDate;
        }

        // @Temporal(TemporalType.DATE)
        @Column(name = "END_DATE", nullable = false, length = Constant.int_10)
        public final String getEndDate() {
                return this.endDate;
        }

        public final void setEndDate(final String endDate) {
                this.endDate = endDate;
        }

        @Column(name = "D_CODE_DESC", length = Constant.int_65535)
        public final String getDCodeDesc() {
                return this.DCodeDesc;
        }

        public final void setDCodeDesc(final String DCodeDesc) {
                this.DCodeDesc = DCodeDesc;
        }

        @Column(name = "D_ITEM", length = Constant.int_64)
        public final String getDItem() {
                return this.DItem;
        }

        public final void setDItem(final String DItem) {
                this.DItem = DItem;
        }

        @Column(name = "HOME_CARD_FINANCE_IND", length = Constant.int_1)
        public final String getHomeCardFinanceInd() {
                return this.homeCardFinanceInd;
        }

        public final void setHomeCardFinanceInd(final String homeCardFinanceInd) {
                this.homeCardFinanceInd = homeCardFinanceInd;
        }

        @Column(name = "COUPON_TYPE", length = Constant.int_45)
        public final String getCouponType() {
                return this.couponType;
        }

        public final void setCouponType(final String couponType) {
                this.couponType = couponType;
        }

        @Column(name = "PROMO_RETAIL", precision = Constant.int_10)
        public final Double getPromoRetail() {
                return this.promoRetail;
        }

        public final void setPromoRetail(final Double promoRetail) {
                this.promoRetail = promoRetail;
        }

        @Column(name = "MARKETING_RETAIL", precision = Constant.int_10)
        public final Double getMarketingRetail() {
                return this.marketingRetail;
        }

        public final void setMarketingRetail(final Double marketingRetail) {
                this.marketingRetail = marketingRetail;
        }

        @Column(name = "STORE", nullable = false)
        public final int getStore() {
                return this.store;
        }

        public final void setStore(final int store) {
                this.store = store;
        }

        @Column(name = "PROMO_ITEM_TYPE", length = Constant.int_11)
        public final String getPromoItemType() {
                return this.promoItemType;
        }

        public final void setPromoItemType(final String promoItemType) {
                this.promoItemType = promoItemType;
        }

        @Column(name = "IS_PROCESS_SUCCESS", length = Constant.int_1)
        public final String getIsProcessSuccess() {
                return this.isProcessSuccess;
        }

        public final void setIsProcessSuccess(final String isProcessSuccess) {
                this.isProcessSuccess = isProcessSuccess;
        }

        @Column(name = "ERROR_CODE")
        public final Integer getErrorCode() {
                return this.errorCode;
        }

        public final void setErrorCode(final Integer errorCode) {
                this.errorCode = errorCode;
        }

        @Column(name = "ERROR_DESC", length = Constant.int_65535)
        public final String getErrorDesc() {
                return this.errorDesc;
        }

        public final void setErrorDesc(final String errorDesc) {
                this.errorDesc = errorDesc;
        }

        @Column(name = "BATCH_ID", length = Constant.int_50)
        public final String getBatchId() {
                return this.batchId;
        }

        public final void setBatchId(final String batchId) {
                this.batchId = batchId;
        }

        @Column(name = "STATUS", length = Constant.int_45)
        public final String getStatus() {
                return this.status;
        }

        public final void setStatus(final String status) {
                this.status = status;
        }

        @Column(name = "CREATE_BY", length = Constant.int_50)
        public final String getCreateBy() {
                return this.createBy;
        }

        public final void setCreateBy(final String createBy) {
                this.createBy = createBy;
        }

        @Temporal(TemporalType.TIMESTAMP)
        @Column(name = "CREATE_DATE", length = Constant.int_19)
        public final Date getCreateDate() {
                return this.createDate;
        }

        public final void setCreateDate(final Date createDate) {
                this.createDate = createDate;
        }

        @Column(name = "UPDATE_BY", length = Constant.int_50)
        public final String getUpdateBy() {
                return this.updateBy;
        }

        public final void setUpdateBy(final String updateBy) {
                this.updateBy = updateBy;
        }

        @Temporal(TemporalType.TIMESTAMP)
        @Column(name = "UPDATE_DATE", length = Constant.int_19)
        public final Date getUpdateDate() {
                return this.updateDate;
        }

        public final void setUpdateDate(final Date updateDate) {
                this.updateDate = updateDate;
        }

}
