// default package
// Generated Nov 14, 2017 11:46:53 AM by Hibernate Tools 5.2.6.Final
package com.homehardware.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "ignitiv")
public class Store implements java.io.Serializable {

	private Integer id;
	private Integer jobId;
	private String storeNumber;
	private String storeName;
	private String storeAdd1;
	private String storeAdd2;
	private String city;
	private String province;
	private String postalCode;
	private String phoneNumber;
	private Integer whse;
	private String storeFormat;
	private String ecommerceInd;
	private String storeServices;
	private String regularHours;
	private String storeContent;
	private Double latitude;
	private Double longitude;
	private String storeWebsiteUrl;

	public Store() {
	}

	public Store(String storeNumber, String storeName, String storeAdd1, String city, String province,
			String postalCode, String ecommerceInd) {
		this.storeNumber = storeNumber;
		this.storeName = storeName;
		this.storeAdd1 = storeAdd1;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.ecommerceInd = ecommerceInd;
	}

	public Store(Integer jobId, String storeNumber, String storeName, String storeAdd1, String storeAdd2, String city,
			String province, String postalCode, String phoneNumber, Integer whse, String storeFormat,
			String ecommerceInd, String storeServices, String regularHours, String storeContent, Double latitude,
			Double longitude, String storeWebsiteUrl) {
		this.jobId = jobId;
		this.storeNumber = storeNumber;
		this.storeName = storeName;
		this.storeAdd1 = storeAdd1;
		this.storeAdd2 = storeAdd2;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.phoneNumber = phoneNumber;
		this.whse = whse;
		this.storeFormat = storeFormat;
		this.ecommerceInd = ecommerceInd;
		this.storeServices = storeServices;
		this.regularHours = regularHours;
		this.storeContent = storeContent;
		this.latitude = latitude;
		this.longitude = longitude;
		this.storeWebsiteUrl = storeWebsiteUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "JOB_ID")
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "STORE_NUMBER", nullable = false, length = 64)
	public String getStoreNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(String storeNumber) {
		this.storeNumber = storeNumber;
	}

	@Column(name = "STORE_NAME", nullable = false, length = 64)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "STORE_ADD1", nullable = false, length = 65535)
	public String getStoreAdd1() {
		return this.storeAdd1;
	}

	public void setStoreAdd1(String storeAdd1) {
		this.storeAdd1 = storeAdd1;
	}

	@Column(name = "STORE_ADD2", length = 65535)
	public String getStoreAdd2() {
		return this.storeAdd2;
	}

	public void setStoreAdd2(String storeAdd2) {
		this.storeAdd2 = storeAdd2;
	}

	@Column(name = "CITY", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PROVINCE", nullable = false, length = 64)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "POSTAL_CODE", nullable = false, length = 64)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "PHONE_NUMBER", length = 64)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "WHSE")
	public Integer getWhse() {
		return this.whse;
	}

	public void setWhse(Integer whse) {
		this.whse = whse;
	}

	@Column(name = "STORE_FORMAT", length = 16)
	public String getStoreFormat() {
		return this.storeFormat;
	}

	public void setStoreFormat(String storeFormat) {
		this.storeFormat = storeFormat;
	}

	@Column(name = "ECOMMERCE_IND", nullable = false, length = 2)
	public String getEcommerceInd() {
		return this.ecommerceInd;
	}

	public void setEcommerceInd(String ecommerceInd) {
		this.ecommerceInd = ecommerceInd;
	}

	@Column(name = "STORE_SERVICES", length = 65535)
	public String getStoreServices() {
		return this.storeServices;
	}

	public void setStoreServices(String storeServices) {
		this.storeServices = storeServices;
	}

	@Column(name = "REGULAR_HOURS", length = 65535)
	public String getRegularHours() {
		return this.regularHours;
	}

	public void setRegularHours(String regularHours) {
		this.regularHours = regularHours;
	}

	@Column(name = "STORE_CONTENT", length = 65535)
	public String getStoreContent() {
		return this.storeContent;
	}

	public void setStoreContent(String storeContent) {
		this.storeContent = storeContent;
	}

	@Column(name = "LATITUDE", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "STORE_WEBSITE_URL")
	public String getStoreWebsiteUrl() {
		return this.storeWebsiteUrl;
	}

	public void setStoreWebsiteUrl(String storeWebsiteUrl) {
		this.storeWebsiteUrl = storeWebsiteUrl;
	}

}
