create table ignitiv.`store`(
   id int auto_increment,
   JOB_ID int,
   STORE_NUMBER varchar(64) NOT NULL,
   STORE_NAME varchar(64) NOT NULL,
   STORE_ADD1 text NOT NULL,
   STORE_ADD2  text,
   CITY varchar(64) NOT NULL,
   PROVINCE varchar(64) NOT NULL,
   POSTAL_CODE varchar(64) NOT NULL,
   PHONE_NUMBER varchar(64),
   WHSE int,
   STORE_FORMAT varchar(16),
   ECOMMERCE_IND varchar(2) NOT NULL default 'N',
   STORE_SERVICES text,
   REGULAR_HOURS text,
   STORE_CONTENT text,
   LATITUDE double,
   LONGITUDE double,
   STORE_WEBSITE_URL tinytext,
   PRIMARY KEY ( id ),
   index STORE_INDEX(STORE_NUMBER,STORE_NAME)

);

create table ignitiv.`ecofees`(
  id int auto_increment,
  ITEM INT,
  PROV varchar(64),
  FEE_AMT double,
  PRIMARY KEY ( id ),
  index ECOFEES_INDEX(ITEM,PROV)
);

create table ignitiv.`item`(
  id int auto_increment,
  ITEM varchar(64),
  ITEM_DESC text,
  HH_SELLING_UOM varchar(100),
  SELLING_UOM_FR varchar(100),
  PRODUCT_CLASS int,
  CATEGORY int,
  FINELINE_CLASS int,
  ITEM_DESC_FR text,
  HH_LUMBER_IND varchar(1) DEFAULT 'N',
  HH_HARDWARE_IND varchar(1) DEFAULT 'N',
  HH_FURNITURE_IND varchar(1) DEFAULT 'N',
  HH_ITEM_SOURCE_CODE varchar(1),
  HH_WARRANTY_EXCHANGE_IND varchar(1) DEFAULT 'N',
  COMMENTS text,
  HH_CTRL_BRAND_IND varchar(1) DEFAULT 'N',
  HH_CONSUMER_ITEM_DESC text,
  HH_CONSUMER_ITEM_DESC_FR text,
  ECOMMERCE_IND varchar(1) DEFAULT 'N',
  BRAND_CODE varchar(64),
  COMMENTS_FR text,
  LIMITED_QTY_IND varchar(1) DEFAULT 'N',
  DISPLAY_ITEM varchar(100),
  PRIMARY KEY ( id ),
 index  BRAND_INDEX(BRAND_CODE),
index ITEM_INDEX(ITEM)
);

CREATE TABLE PRODUCT_ATTRIBUTE( PRODUCT_ATTR_ID VARCHAR(64) NOT NULL,
JOB_ID INT,ATTRIBUTE_NAME VARCHAR(64),
ATTRIBUTE_NAME_FR VARCHAR(64),
IS_PROCESS_SUCCESS VARCHAR(1) DEFAULT 'F',
ERROR_CODE INT,
ERROR_DESC TEXT, PRIMARY KEY (PRODUCT_ATTR_ID));

CREATE TABLE PRODUCT_ITEM_ATTRIBUTES(PRODUCT_ATTR_ID VARCHAR(64) NOT NULL,
JOB_ID INT,
ITEM VARCHAR(64) NOT NULL, 
ATTRIBUTE_VALUE VARCHAR(64),
ATTRIBUTE_VALUE_FR VARCHAR(64),
IS_PROCESS_SUCCESS VARCHAR(1) DEFAULT 'F',
ERROR_CODE INT,
ERROR_DESC TEXT, 
status varchar(64),
PRIMARY KEY (PRODUCT_ATTR_ID,ITEM));


CREATE TABLE EXT_DESC (
ID int(11) NOT NULL AUTO_INCREMENT,
ITEM VARCHAR(64) NOT NULL,
LANGUAGE VARCHAR(64),
DESCRIPTION TEXT,
TYPE VARCHAR(64),
IS_PROCESS_SUCCESS VARCHAR(1) DEFAULT 'F',
ERROR_CODE INT,
ERROR_DESC TEXT,
PRIMARY KEY (ID)
);

CREATE TABLE ECO_FEES (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM` varchar(64) NOT NULL,
  `PROV` varchar(64) NOT NULL,
  `FEE_AMT` double NOT NULL,
  `IS_PROCESS_SUCCESS` varchar(1) DEFAULT 'F',
  `ERROR_CODE` int(11) DEFAULT NULL,
  `ERROR_DESC` text,
  PRIMARY KEY (`id`),
  INDEX `ITEM_INDEX` (`ITEM`),
  INDEX `PROV_INDEX` (`PROV`)
) ;

CREATE TABLE `ecofees` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ITEM` varchar(64) DEFAULT NULL,
  `PROV` varchar(64) DEFAULT NULL,
  `FEE_AMT` double DEFAULT NULL,
  `ECO_FEE_DESC` varchar(100) DEFAULT NULL,
  `ECO_FEE_DESC_FR` varchar(100) DEFAULT NULL,
  `IS_PROCESS_SUCCESS` varchar(1) DEFAULT 'F',
  `ERROR_CODE` int(11) DEFAULT NULL,
  `ERROR_DESC` text,
  `BATCH_ID` varchar(50) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT 'INITIAL',
  `CREATE_BY` varchar(50) DEFAULT NULL,
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_BY` varchar(50) DEFAULT NULL,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `ECOFEES_INDEX` (`ITEM`,`PROV`)
) ENGINE=InnoDB AUTO_INCREMENT=15562 DEFAULT CHARSET=utf8;

create table dyn_attr_info(`id` int(11) NOT NULL AUTO_INCREMENT, `DYN_ATTR_ID` INT(11),
`DYN_ATTR_DESC` varchar(100) DEFAULT NULL,
`DYN_ATTR_DESC_FR` varchar(100) DEFAULT NULL,
`IMAGE_ID` int(11),
`LANGUAGE` varchar(100) ,
`ERROR_CODE` int(11) DEFAULT NULL,
 `ERROR_DESC` text,
`BATCH_ID` varchar(50) DEFAULT NULL,
 `STATUS` varchar(45) DEFAULT 'INITIAL',
 `CREATE_BY` varchar(50) DEFAULT NULL,
 `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
 `UPDATE_BY` varchar(50) DEFAULT NULL,
 `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
  
  
  CREATE TABLE `retail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM` varchar(64) DEFAULT NULL,
  `STORE` int(11) DEFAULT NULL,
  `RETAIL` decimal(10,2) DEFAULT NULL,
  `IS_PROCESS_SUCCESS` varchar(1) DEFAULT 'F',
  `ERROR_CODE` int(11) DEFAULT NULL,
  `ERROR_DESC` text,
  `BATCH_ID` varchar(50) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT 'INITIAL',
  `CREATE_BY` varchar(50) DEFAULT NULL,
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_BY` varchar(50) DEFAULT NULL,
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32169 DEFAULT CHARSET=utf8;